### ISSUE TITLE
Transitive Transfer not working

### ISSUE THREAD

**Issue by ice09** [CirclesUBI/circles-contracts#112]
I have three addresses,

trusthubmerchant: https://circles.garden/profile/0x9FaA986911c4423ad9895805BEE4a566DD11120D
trusthubcustomer: https://circles.garden/profile/0xC29D7Ab348b2dA3B59eE80A8492bEDFaDf350AEF
twitterTrusthubNoCond: https://circles.garden/profile/0xA485e9295ef16143891F4A0d77C060E87EA59C87

twitterTrusthubNoCond trusts both others mutually, however I cannot transfer from customer to merchant.
I would have even thought this should work with trust trusthubmerchant > twitterTrusthubNoCond < trusthubcustomer and no mutual trust, but it does not even work with all trusts mutual.

Please tell me if there is a better place for this issue.

_Note: x-posted this issue in API_

**Comment by ana0** [comment]
Hi @ice09 - I see you also opened this issue in the api repo, and unless you have a good test case otherwise, I think it most likely has to do with some issues we're working on due to pathfinding/the size of the trust graph.  I'm gonna close this one, and leave it open over there for now

**Comment by ice09** [comment]
Sure, however, I have good testcases for this. Will add to the other issue then.

**Comment by ana0** [comment]
Yes, I mean a testcase running against the contracts specifically. As far as I can tell your test case is running against the gui, and through the api
