### ISSUE TITLE
Give personal currency sensible names / allow users to personalize the name on creation

### ISSUE THREAD

**Issue by Jake-Gillberg** [CirclesUBI/circles-contracts#12]

**Comment by edzillion** [comment]
I have thought about this before:

* Would we need some kind of oversight to make sure people didn't make offensive named coins?
* There is a gamifying element to this: I am sure there will be people who will collect a coin of each of their friends; they may also want to keep coins given them by famous people etcetera
* A cool idea that I have pondered in the past: Users can add a string to coins either when they mint them or when they first transfer them. This could serve as a way to add some kind of 'cultural history' to the system. People might just thank the reciever or congratulate them on some life event, or even just write a motivational message or a note for posterity. This would take an order of magnitude more 'monitoring', in whatever form that takes, and there are other issues, but tell me why it's a crazy idea anyway.

**Comment by ana0** [comment]
>We would need some kind of oversight to make sure people didn't make offensive named coins. How easily could this be automated?

Offensive I wouldn't worry about, but we should sanitize for code-injection:  https://hackernoon.com/how-one-hacker-stole-thousands-of-dollars-worth-of-cryptocurrency-with-a-classic-code-injection-a3aba5d2bff0

**Comment by JuliointheStudio** [comment]
hello! can you give me an example of how symbols look like? I agree that people should be able to set their own name.. the decimal thing I have no clue about but the symbol seems to be important.. :)

**Comment by edzillion** [comment]
©

**Comment by ana0** [comment]
Decimals is a weird software thing, because the evm doesn't have good support for floating point numbers.  Numbers are stored as integers based on their least significant digit.  So like, for 20.00 USD, the evm would store 2000 and decimals = 2. For ether, it's 18.  Most tokens use 18 too. It's kind of technical thing, not something users need to think about.  

Symbol is like a ticker symbol, like 'USD' or 'ETH'.

**Comment by edzillion** [comment]
> Symbol is like a ticker symbol, like 'USD' or 'ETH'.

hmmm. Seems like `CRC` isn't taken, at least according to wikipedia (which is kinda cool cos it also means Capablanca Random Chess)

https://en.wikipedia.org/wiki/List_of_cryptocurrencies

**Comment by ana0** [comment]
Ok, gonna go with `CRC` for now
