### ISSUE TITLE
What is the role of an organization

### ISSUE THREAD

**Issue by ana0** [CirclesUBI/circles-contracts#24]
Organizations can accept ubi tokens, but do not receive a ubi. 

- Can transitive transactions pass through an organization?
- Can they be validated?
- Can organizations trust users?
- Can users trust organizations?
- How are they 'owned' in a blockchain sense?

**Comment by ana0** [comment]
Conclusions, from a convo with @edzillion @saraswathi and @JuliointheStudio:

- transitive transactions can not pass through an organization
- organizations can not trust users
- users can not trust organizations
- organizations can not get validated
- organizations can trust validators

Organization ownership needs to get picked up still

**Comment by dumpa** [comment]
Sorry if this is disscussed somewhere else and I missed it, but why do we need organizations to receive transactions. We can have organizations which are a bunch of people with affinities. But we transact with people. Organizations help people trust each other.

**Comment by ana0** [comment]
Hey! The organization role is here is maybe more like a business, which does help people trust each other indirectly, but mostly is selling goods or services. An example would be the cafe Circles is planning to administer, Cafe Grundeinkommen - when you buy a coffee at the cafe, you pay the cafe, not the barista directly. Then the cafe pays the barista (probably hourly).

**Comment by dumpa** [comment]
Ok, If the cafe is transparent enough I can trust Cafe Grundeinkommen. I don't see why not. And if I see something strange i can stop trusting it. I believe trust is something people give it is not asked.

**Comment by ana0** [comment]
What trust allows in this system is transitive transactions - trying to summarize here, but I think the reasons the team is consensing around not allowing on-chain trust connections to organizations is that, if users trusted an organization, it would allow a one-hop transitive transaction to anyone else who purchases coffee at the cafe, and that seems to begin to disintegrate the powers of the trust web as anti-sybil defense.

**Comment by ana0** [comment]
Closing because organizations are descoped under the current mvp
