### ISSUE TITLE
Explore Options for issuing the payout on a certain day of the week.

### ISSUE THREAD

**Issue by edzillion** [CirclesUBI/circles-contracts#3]
How would we best approach this?

What we want is to have a payout happening for everyone worldwide on a Friday, either all at the same time worldwide, or at a certain time in each timezone/region.

I talked briefly with @MrChico on this and he suggested that it might be possible to have the contracts creating money continuously but have the client only call for the new balance on Friday?

@shkfnly and @ana0 you had some thoughts on this on the call can you note them here?

**Comment by ana0** [comment]
Didn't get notified about this - but my suggestion the other day was to define balance as a function of blocktime, creation of contract time, and spent tokens

**Comment by ana0** [comment]
Jake is suggesting the same thing

**Comment by dumpa** [comment]
If it is going to have a timestamp I would go for daily or less (hourly). Most people in the world live by the day. They need money to survive the day, not the week,

**Comment by MrChico** [comment]
I would still argue for having the minting / burning happening continuously in the contracts and then we display it however we want on the front end

**Comment by ana0** [comment]
Think it's not so simple, the old contracts overrride `getBalance` for example.  Doing this would be a concern if we'd like balances shown in the Circles ui to reflect balances shown in other uis (Etherscan, Metamask, etc)

**Comment by ana0** [comment]
Closing because payout is continuous in the current mvp
