### ISSUE TITLE
What chain should we use for the pilot?

### ISSUE THREAD

**Issue by ana0** [CirclesUBI/circles-contracts#41]
As per @xwvvvvwx, Kovan is being deprecated. POANetwork is still a contender (https://poa.network/). This is a thread for discussion/suggestions

**Comment by xwvvvvwx** [comment]
PoA is an interesting alternative, although I'm not super convinced by the trust assumptions, we would be placing the security of our network in the hands of the following 21 US based individuals: https://validators.poa.network/poa-dapps-validators.

**Comment by xwvvvvwx** [comment]
@ana0 I think https://loomx.io/ is doing something similar? Do you know anything about them?

**Comment by xwvvvvwx** [comment]
We should also think about running our own chain again, it would put us on a better path towards utilizing the trust graph as part of our consensus mechanism.

**Comment by xwvvvvwx** [comment]
Maybe relevant: aws managed blockchain: https://aws.amazon.com/managed-blockchain/

**Comment by ana0** [comment]
Closing because using xDai in the mvp
