### ISSUE TITLE
Create a proxy on signup for formatting metatxs

### ISSUE THREAD

**Issue by ana0** [CirclesUBI/circles-contracts#42]
Pros and cons?

Con of the current approach is we need to whitelist relayers/have special methods on all contracts for the relayer. 

Adding a proxy would allow the main hub and token to not know about the relayer, and add a nice path for upgradability with further user features, like social recovery.

**Comment by xwvvvvwx** [comment]
*pros*:

- Core doesn't need to know about relayers
- If the relayers go bad / go down, then the contracts are still usable

*cons*

- Slightly higher gas cost
- Might make end user auditing / verification harder (due to additional layer of indirection)

**Comment by ana0** [comment]
Closing because the new MVP plan uses gnosis safe for this functionality
