### ISSUE TITLE
Should issuance rates change? if so, how?

### ISSUE THREAD

**Issue by Jake-Gillberg** [CirclesUBI/circles-contracts#5]
Considering:
- Allowing users to set a "cap" of issuance rates they are willing to accept. Allow users to update their own issuance rates. When a user (Alice) updates their issuance rates, all of those who trust Alice and who's "cap" is lower than the updated rate will break their trust relationship with Alice.

**Comment by innsmouthrain** [comment]
Consensus from our last retreat in NYC was that issuance rate should be changed community-wide through physically held meetings for this pilot

This is of course a super interesting topic that we will want to explore further outside the scope of the pilot.

**Comment by edzillion** [comment]
@Jake-Gillberg this is a very interesting proposal.

> Do we have to worry about this if we are able to change the issuance rates? If we have the ability to "drop it to 0" or "increase it to infinity", would that mean we are "altering people's accounts"?

This is a serious issue and we should ask a legal person asap.

In general I think it might help if you describe your motivations for such a system. What would a multiple-issuance system look like and would it not violate a core principle of Circles: _A monetary system where money issuance is equal between all users_

**Comment by JuliointheStudio** [comment]
The issue I see with having different people with different issuance rates would be that the parity between all users value will change. If you have some users whose money is worth more than others, then we have a problem. How to maintian the parity/equal value of money between users while allowing for your proposal Jake?

**Comment by edzillion** [comment]
> If you have some users whose money is worth more than others,

This isn't a direct outcome of differing issuance rates. They would just have different amounts. Given two similarly productive people, the person with the lower issuance rate would _tend toward_ being worth more than someone with a bigger issuance.

If we ended up having a really clear split between two camps, one of which had refused an issuance increase _and_ these camps were easily identifiable by the users *then you could* have a situation of two exchange rates. In reality there would probably be 80% of people with the current issuance, and 20% with a mix of lower rates (many of these accounts may be inactive) - this is a much less clear system for users to make value judgements of peoples currencies based on some kind of categorisation.

**Comment by Jake-Gillberg** [comment]
> How to maintian the parity/equal value of money between users while allowing for your proposal Jake?

IMO we can't. You can't stop these sorts of trades "uneven" exchange rates from popping up unless you have controls on where / how people can spend this currency, but I don't think we want to go this direction.

I think the best we can do is create social norms / system defaults of 1 to 1 exchange rates.

This "who has the ability to change the issuance rate of their currency" question is an interesting one, because we are asking "by who's responsibility / authority do these system defaults change". My current preference is that the sole authority to make these changes lies on the individual currency creator, and it is up to us (the Circles team) to communicate and support proposed "defaults".

**Comment by ana0** [comment]
>IMO we can't. You can't stop these sorts of trades "uneven" exchange rates from popping up unless you have controls on where / how people can spend this currency, but I don't think we want to go this direction.

>I think the best we can do is create social norms / system defaults of 1 to 1 exchange rates.

I'm agree with all of this, actually and my biggest concern for circles is that we'll fail to adequately seed these social norms.  

For the global-community-set issuance rate - I'm assuming this is going to be stored in some contract.  Maybe a global vars contract, maybe a library that other tokens are proxies of .. either way, it seems to me it should only be updatable via multisig.  Who are the trustees of the multisig keys? How many of them there are? They should probably be representative of circles users, but how are they chosen and how do we determine that?  

As for user-set individual issuance rates .. there are things I like about this idea.  I like empowering users, and I like decenter-ing power.  We could allow for a user override here, and then flag/alert users who are trusting someone who's chosen to not use the global rate (is higher, is lower, divergence of more than x, any divergence, etc).  But then do we also allow users to override the flag/alert?  What is the incentive to override here ... disbelief in and disenfranchisement from the circles governance processes?  I like to keep in mind that we can never stop users from forking our work - we can only ever make it harder or easier.  It seems to me there's an upper bound on the ways we are obligated to make it easier.  

Biggest danger of this whole thing is scope creep.  For the purposes of the pilot, what are we actually hoping to test?  @JuliointheStudio mentions a set of hypotheses in his recent research roadmap ... think defining those will be helpful in knowing how far to travel down any of these particular rabbit holes

**Comment by ana0** [comment]
Sorry I gone and wrote an essay

**Comment by xwvvvvwx** [comment]
> not violate a core principle of Circles: A monetary system where money issuance is equal between all users

A variable issuance rate seems most interesting at a global scale, where a Circle in e.g. Switzerland will probably have a different purchasing power from a Circle in e.g. Liberia. So in this case a variable issuance rate would guarantee an equal purchasing power between all users instead of an equal issuance rate.

There does not appear to be a clear consensus on:

1. Whether this is desirable 
1. How this would be achieved

As the pilot will only be run in Berlin, a single global issuance rate for all users seems sufficient.

How that issuance rate is set (and modified) is a hard problem by itself. Most of this kind of decision making will happen off chain (and I don't think any amount of fancy smart contract engineering will change this), so we should try to create spaces where users can be involved in the decision making process as much as possible.

> I think the best we can do is create social norms / system defaults of 1 to 1 exchange rates.  

I would also agree that good governance will always rely on strong social / community norms and our focus early on should be on defining and spreading these.

**Comment by ana0** [comment]
Closing because I think consensus for a global issuance rate remains
