### ISSUE TITLE
Should we add some form of Demurrage?

### ISSUE THREAD

**Issue by Jake-Gillberg** [CirclesUBI/circles-contracts#6]
> From Julio, 20 sept 2018:
The Paradox of Wealth, or the Lauderdale Paradox https://monthlyreview.org/2009/11/01/the-paradox-of-wealth-capitalism-and-ecological-destruction/
Im thinking of this in relation to circles and demurrage. What would happen when people start putting things of use value into circles (like care work), granting them a number and sending it over to the person who performed the work. The problem with most political economy we have from those times is that their ideas of what money is were very rigid, seeing them as commodities and not as social relations. Now, with credit theories of money, what would happen if care becomes render visible and important through its valuing,,, demurrage is a system by which the value of money loses is lost if its not used. The main argument for it is to avoid hoarding (savings as we know it in daily life)
demurrage is a way of giving life to money and changing the nature which it holds today i.e. as an interest bearing debt.
if i get money from a bank, with a fixed or variable interest, the amount of money whch i must pay back through my labor is higher than the amount which i was given. With demurrage + a basic income, you have a constant amount of money which dies out slowly, like any other living thing. its kinda like an ecology of money.
so say i have 100 circles every month and we set the demurrage rate at some level like, say, one month. Let's say my rent is 50 circles and I pay for it every month with my basic income.. the other 50 i can use for spending money /exchanging things with others and at the end of the month, whatever is left dissapears or rots away, and a new basic income is issued.
this is a practical way of putting limits to consumption within the system.. in real life it will of course co exist with fiat currencies, which work on a hoarding/circulation dialectic and continously grow as new money is issued.
now....for money to be able to buy the basic things we need in life, we must first create an ecosystem which allows that to happen. This is one of the goals of Circles. A basic income will only happen as the money gains value. The value of money comes from its social life i.e. from all the interactions in which money is submerged, all the different transactions which bring its value into being. One way to do this is by asking the users what do they need to have a basic livelihood and look for actors accordingly.
food, housing, energy, sanitation, there are many different things that are needed for people to be able to live a basic life. What are those things in Berlin? we must identify them as the project runs. Part of research is to document this but most importantly, to translate this information to the community and see how we get new people onboard.
@edzillion says its too much to add demurrage to the system in the first run but i think its just a system design question. @jake.gillberg check this out: https://en.wikipedia.org/wiki/Demurrage_(currency)
it shouldnt be too hard to embedd it in the system, or is it?
@martin.lundfall i need your brains on this one.
http://userpage.fu-berlin.de/roehrigw/fisher/ Irving Fisher wrote a book during the Depression, called Stamp Scrip, where we outlines the experiments at demurrage credit systems that were going on at the time in the US. These were all, for the most part, forgotten by most. But worth to look into: http://userpage.fu-berlin.de/roehrigw/fisher/

**Comment by innsmouthrain** [comment]
I would assume it is too challenging for the pilot, as we agreed on last time we met.

It's super interesting however and I wish for us to explore this topic more.

Looking at the user experience I think it has very dramatic effects, both as advantages and disadvantages. It could make Circles a "worse" currency that you want to spend before your fiat, which is cool. It is also very alien, and I think users might have a hard time liking a currency that disappears.

Notably I don't think of this as stopping hoarding however, and instead, users will always be tempted to use their last bit of money which is about to disappear. They will buy things they don't need, things that last. They might even start buying and trading long-lasting products with eachother that they don't use, essentially creating a sub-currency of their own to counter-act the demurrage.

**Comment by edzillion** [comment]
I agree with all of what @innsmouthrain said, including that we shouldn't include it in a pilot. I have a few more reasons why I think it might be much more difficult to implement:

1. The start of a monetary system is like the big bang, it only happens once in the history of an economic universe; and the rules may be radically different at that early stage than when the system has stabilised. In fact, as long as Circles is growing, it will benefit our management of the currency as it will be a counter to inflation; e.g. the denominator of the following fraction will be increasing:
amount of currency _in use_ / amount of productive users
Ideally (and this is certainly helped by Circles design) these would increase at the same rate. If there is more currency per user we will have inflation, if there are more users we would have deflation (with a ton of caveats, but we're simplifying here). I believe we want to err on the side of deflation.
So getting these two to increase in tandem is basically the biggest challenge we face, and could thought of as perhaps the core proposition of Circles: _How do you create value through scarcity of a currency that is free and available?_
Who could even know how Demurrage would interface with this? 
**Remember that even a Money Pyramid works as long as it is still growing**

2. As a corrolary to the above; we might as well throw out any idea of maintaining dollar parity with the introduction of a Demurrage fee. I can't see how that would be possible; although I think there is room for innovation on this, but ...

3. It's just too much, it reminds me of when you see those threads on reddit or whatever and people are (semi) jokingly adding in all the things they would have in an idealised political system:
> And we'll have LVT
> Yeah and we'll have a unified tax rate, fuck this capital gains BS
> Yeah and don't forget FTT etc, to pay for a UBI
> also Sortition, it's the coolest idea ever
> Yeah and drawing political offices by lot, isn't that like sortition

It will take a huge leap of faith for your average Jane to feel comfortable with Circles, if we add too many radical ideas we will just put people off.

**Comment by JuliointheStudio** [comment]
So.. after a long and tiring discussion with Ed, I think demurrage could be added as a second installment of the system design and it could act as a potential counter to inflation, in case we face high levels of it. From a research perspective, if we add too many things at once, it will be hard to know what are the actual effects of the different aspects of the system. Demurrage is basically a way of installing degrowth into the system and it is the reason why people have a difficulty rapping their head around it. Our system falls on the logic of capital insofar as the money supply is constantly increasing. Now, for the sake of having conceptual clarity it would be useful to think of Circles as a mutual exchange credit system which can provide people with a basic livelihood once we have enough people in the network interacting with each other. It will not be a basic income until we reach those levels. Before that, our focus should be on getting the details and functioning of the system right. Demurrage can be used in a subset group of people or at a later stage if we face big inflationary problems (which we probably will). In this way, it makes more logical sense to add demurrage and then compare the effects before and after its implementation. 
love and peace

Juliointhegithubbio

**Comment by Jake-Gillberg** [comment]
Sounds like a "close as not doing" for now then!

**Comment by Jake-Gillberg** [comment]
Based on @JuliointheStudio 's comments today, we should maybe leave this open for discussion.

**Comment by edzillion** [comment]
This has been decided. We will have system-wide demurrage from the start, but set the rate at a nominal level at the beginning.
