### ISSUE TITLE
What should trust relationship limits look like?

### ISSUE THREAD

**Issue by Jake-Gillberg** [CirclesUBI/circles-contracts#7]
How the circles-sketch contracts worked:
> From Martin L.
@martin.koeppelmann Yes, limiting the trust connection does make sense. The current, quick and dirty implementation has the trust connection not as a binary thing, but when person A trust person B they are doing so up to a certain amount. In other words, when A trusts B, she sets a maximum amount of B tokens she are willing to automatically (through the transitive transfer) exchange 1:1 with _any_ other circles token she owns.
This is a lot simpler from an implementation perspective than varying everybody's trust relation whenever a new person joins your trust network, and also allows for more flexibility and personal tweaks. That said, I think setting the trust limit proportional to the amount of connections you have serves as a good default – that is still a reasonable choice to implement on the application layer

## Köppelman's Trust Quota
> martin.koeppelmann 11:16 PM
https://chat.joincircles.net/channel/general?msg=PSPXEy2iqLTtAQjiB
hey guys. @harriet, @karenina and me had today an interesting discussion about the 1:1 relationships and wether or not they should be "unbounded" (you can exchange unlimited tokens 1:1)
One suggestion that evolved in this conversation was that it should be limited according to the trust graph.
The basic idea is: If I am connected to N people than the capacity of a connection is only unlimited if the other person is also connected to ALL N people.
If the person is only connected to M out of N the connection is limited to M/N
That mean if e.g that person is connected to half of the people the connection is limited to 1/2
If the limit is 1/2 it means that I will never exchange tokens in a way that I end up holding more than 1/2 of all my circles of that person.
So if I hold t Circles in total I stop exchanging tokens 1:1 with a person if I already hold at least M/N * t tokens of that person.
I think this approach can solve a bunch of problems @martin.lundfall @zandy @wouter @edzillion - what do you think?

>edzillion 5:03 PM
that's a really elegant solution @martin.koeppelmann - I was thinking that it would be limited by distance instead, so that if you directly trust someone you will allow 100% and then maybe divide by .6 each time so that a person 2 hops away can exchange 60%, the next hop 36% etc.
In fact I bet your system would share the same decreasing-over-hops feature, since those further away from you on the graph are likely to have less connections in common
Does it encourage or hinder making new connections though?

>karenina 5:14 PM
we thought it'd rather encourage new connections as it lowers the risk of being stuck with coins you cannot use. other question: does it discriminate against people who do not have a large network in the Circles world (for example if they come from marginalized communities?)

>aleeza 10:31 PM
@karenina @harriet @martin.koeppelmann It is a really nice elegant baseline but technically I'd say yeah, it still discriminates against those with a weaker network... I think it is an improvement on the default, as it will give people a "lower bound" for how much of their friends' coins to accept. We can set M/N as the minimum and still allow "generous" people to accept a higher percentage of weak coins against their own. That doesn't solve the actual problem though. Since that lower bound doesn't actually reflect use value: You may not be spending with everyone in your network evenly (unless living on a commune), which means just because somebody shares your network 90%, the "valuable" transaction potential is actually with that 10% connection outside the major network (assuming a "marginalized" community). If you're the bridge to that 10%, one enterprising buddy could quickly use up all of your personal coins that are accepted at that valuable outside connection. The only way to actually solve this problem is to get that marginalized community properly integrated... >>> Which is where this could be super interesting! Because it will encourage _diverse_ connections, aka new connections with people who do _not_ share the rest of your network, and thus are way more limited in the percentage of your coins they can transact with. That is a really great incentive system for creating a stable, distributed, interconnected trust network... 🙂

>moth 8:27 AM
@aleeza I'm still thinking about this new algorithm and its effects and I will post my thoughts below, but first I'd like to share my thoughts on scaling in this public chat like I have been so far in our closed meetings. 
Personally I don't think personal currencies can ever scale well enough to actually be allowed to have this problem. 
When it reaches the point where discrimination against those with weaker network matters, the network should be big and stable enough to shed it's baby skin and grow up, switching its personal currency system to some kind of group currency and instead start acting as its own cell in a larger organism; This would be analogous to zooming out from proton/neutron scale and start looking at atoms and suddenly you care about molecules and different rules apply. Scaling means you need to start managing things like inflation which requires governance so as far as I know what we have to do to achieve this is build a group currency with custom governance. We can supply a recommended set of governance methods and I'm currently reading about this, but ultimately it will be up to the community itself.
But the key here is that just like the protons in the atoms, personal currency particles exist within the group currency atoms and is what keeps them stable.
Here I will puke out some slightly organized thoughts on this new way of limiting exchange, @martin.koeppelmann @edzillion @aleeza @karenina . I'm most interested in how the results will differ from our previous mechanisms. Asking whether trust connections should be unbounded should already be clear, no they can't - it would mean it's too big a risk to ever trust a new node and hub nodes would be depleted instantly of their own currency.
In what Andy proposed as limited trust in Athens last summer, you defined a certain amount of personal currency to be exchangable per time period per trust connection, (e.g. let's say we mint 1 CircleCurrency/s and for new-guy-Bob you allow the 1:1 exchange 1/100 minted currency or one per 100s and for old-friend-Alice you allow 50/100 or 1/2 since she's well established already and has many trust connections in common with you). 
In this new model, I'm gonna call it Köppelman's Trust Quota for now, saying that the capacity is unlimited if you are both connected to the same set, N, is redundant since you will never need to do transitive transactions if you all have the same direct trust connections - you can simply transact with your target directly. In KTQ you would allow 1/2 of your currency to be Alice's but only 1/100 to be Bob's. Bob is one of your trusted connections and you can receive payments in BobCoin, so this can lead to a curious situation: you have 200 of your own coins, Alice buys your old bicycle for 400 BobCoin and already you hold 2/3 of your currency as BobCoin meaning Bob can not exchange with you for a substantial amount of time (depending on when you spend his currency or how much other currency you accumulate).
They both limit the risk of trusting new nodes, good, so they should both allow (encourage) you to trust new nodes. Athens limited trust (ALS?? 🤡 ) is not defined automatically in the same way, but is set up "manually" or more likely through some other automated process (in the app). ALS does not take into account in any way how much or what type of currency you are holding right now.
How is the quota calculated? Does it happen off-chain and continously consulted?
Will these different methods lead to different behaviours? Is there ever a reason for someone to want to manually set the exchange limit of a certain connection and disregard the automated limit set by something like KTQ?

**Comment by innsmouthrain** [comment]
I think trust limits should have a very basic implementation because we should focus on leaving the personal currency step quickly, heading for community currency.

I don't think personal currencies can scale well and it's dangerous for us to try to treat them as if they would. They are a sybil defense for bootstrapping and a decentralized fallback in case of corruption or dysfunction on higher levels.

Limits to trust should exist to allow risk mitigation for new personal trust connections in case they are sybils or because they will use up all your own coins through transitive exchange. If it does these things I think it's finished.

Worrying about discrimination at this level I think is misdirected, intsead we should treat personal currencies as _purely_ a sybil defense mechanism and hurry up and reach community currency territory, where scaling is much easier (and discrimination doesn't happen in this way).

**Comment by edzillion** [comment]
> I think trust limits should have a very basic implementation because we should focus on leaving the personal currency step quickly, heading for community currency.

> ...

I disagree entirely, and I am guessing that this opinion would be controvertial with the wider group as I haven't heard it articulated before. 

Simply put, I am very wary of group currencies in general as I think we might end up recreating the system we are trying to replace (e.g. _one money to rule them all_ and boo to anyone who can't or won't take part)

**Comment by ana0** [comment]
Trying to summarize the existing proposals for managing trust limits ... There seems to be some consensus that trust needs to be limited. The question is how?

There are three main ways to do so that I see being presented. 

1) Suggested by Köppelman: The amount of tokens tradable with any other person is limited by the subset of overlapping trust connections they share.  eg. If they share 1/2 their trust connections, they will never exchange tokens in such a way where more than half their total tokens are from that person.

2) Suggested by Ed: The amount of tokens tradable decays with each hop of a transitive transaction. eg. A one-hop transaction can trade 100% of their tokens, but a the second hop decays by _n_ and can only be at most 100*_n_%

3) Suggested by Andy (I think?): Users set a trust-limit with each connection (and maybe this is recommended by the app in some way) and there's also a system wide epoch parameter. The trust limit is that maximum amount a user can exchange along that trust connection per epoch. eg. A user can transfer _x_ `CRC` to another user per day.

**Comment by ana0** [comment]
Some notes: @saraswathi and I talked this through, focusing on usability concerns. We arrived a preference for option 3, with the actual trust limit amount being recommended offchain by something like option 1. The user could still have the freedom to override the recommended amount if they wanted.

This does lead to a problem where Alice trusted Bob early on, when they didn't have a strongly overlapping trust graph, but overtime as more mutual friends joined Circles, the trust limit should probably be updated. Could be helped by adding an offchain feature that checks for significant changes to trust network overlap and prompts Alice to update the onchain trust limit. Could even be framed as a reward, ie "Achievement unlocked! Your trust network with Bob is really strong - do you want to update your trade limit?" etc

Still needs final decision

**Comment by ana0** [comment]
Closing, we have decided to use percentage of totalsupply as the trust limit parameter, and to recommend a flat rate system wide for the MVP
