### ISSUE TITLE
Upgrade the Safe

### ISSUE THREAD

**Issue by ana0** [CirclesUBI/circles-contracts#82]
There are newer versions of the gnosis safe, and ours has a number of very old dependencies, preventing us from updating our version of node itself.  

We should use the newest safe, and clear out these dependencies

**Comment by adzialocha** [comment]
:+1: This will break the relayer, so we should do this simultaneously with upgrading the relayer

**Comment by adzialocha** [comment]
Related issue: https://github.com/CirclesUBI/safe-relay-service/issues/14
