### ISSUE TITLE
Make max. transfer steps adjustable?

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-contracts#92]
Does it make sense to make the maximum transitive transfer steps a configuration variable which can be changed after deployment?
https://github.com/CirclesUBI/circles-contracts/blob/master/contracts/Hub.sol#L234

I wonder if block gas limits are dynamic and also different depending on the chains one is running? Also, is the current value somehow verified or guessed?

Maybe we can make it adjustable as every more step gives a larger potential for more complex transactions, so we don't limit ourselves with a static / too low value?

**Comment by ana0** [comment]
It's totally arbitrary right now, we could realistically remove it from the contracts and just let people run out of gas
